#! /bin/sh

mv Altered_Chrome_Bold.ch8 ALTERE-1.CH8
mv Altered_Chrome.ch8 ALTERE-2.CH8
mv Altered_Chrome_Script.ch8 ALTERE-3.CH8
mv Altered_Chrome_SemiBold.ch8 ALTERE-4.CH8
mv Anarchist.ch8 ANARCH-1.CH8
mv Anarchist-Heavy.ch8 ANARCH-2.CH8
mv Anarchist_Heavy.ch8 ANARCH-3.CH8
mv Anarchist_Short.ch8 ANARCH-4.CH8
mv Anchovy.ch8 ANCHOVY.CH8
mv Anvil_Alternate.ch8 ANVIL_-1.CH8
mv Anvil.ch8 ANVIL.CH8
mv Area51.ch8 AREA51.CH8
mv Area51_Overwide.ch8 AREA51-1.CH8
mv Area51_Serif_Bold.ch8 AREA51-2.CH8
mv Area51_Serif.ch8 AREA51-3.CH8
mv Around.ch8 AROUND.CH8
mv Atlas.ch8 ATLAS.CH8
mv Authorized.ch8 AUTHOR-1.CH8
mv Authorized_Edge.ch8 AUTHOR-2.CH8
mv Babyteeth.ch8 BABYTE-1.CH8
mv Bamboo.ch8 BAMBOO.CH8
mv Bauhaus.ch8 BAUHAUS.CH8
mv Beachball.ch8 BEACHB-1.CH8
mv Beachball_Short.ch8 BEACHB-2.CH8
mv Beastly.ch8 BEASTLY.CH8
mv Binnacle_Bold.ch8 BINNAC-1.CH8
mv Binnacle.ch8 BINNACLE.CH8
mv Binnacle_Oblique.ch8 BINNAC-2.CH8
mv Blood_Rain.ch8 BLOOD_-1.CH8
mv Broadwary.ch8 BROADW-1.CH8
mv Bubblegum.ch8 BUBBLE-1.CH8
mv Bubblegum_Round.ch8 BUBBLE-2.CH8
mv Byteletter.ch8 BYTELE-1.CH8
mv Cabaret_Bold.ch8 CABARE-1.CH8
mv Cabaret.ch8 CABARET.CH8
mv Cabaret-Pro5.ch8 CABARE-2.CH8
mv Cabaret_Semi_Bold.ch8 CABARE-3.CH8
mv Cage_Bold.ch8 CAGE_B-1.CH8
mv Cage.ch8 CAGE.CH8
mv Calstone.ch8 CALSTONE.CH8
mv Calstone_Heavy.ch8 CALSTO-1.CH8
mv Caprica.ch8 CAPRICA.CH8
mv Carton_Bold.ch8 CARTON-1.CH8
mv Carton.ch8 CARTON.CH8
mv Carton_Tall_Caps.ch8 CARTON-2.CH8
mv Chest_Burster_Bold.ch8 CHEST_-1.CH8
mv Chest_Burster.ch8 CHEST_-2.CH8
mv Chit_Bold.ch8 CHIT_B-1.CH8
mv Chit.ch8 CHIT.CH8
mv Chunky_Monkey.ch8 CHUNKY-1.CH8
mv Cinema_Bold.ch8 CINEMA-1.CH8
mv Cinema.ch8 CINEMA.CH8
mv Cinema_Condensed.ch8 CINEMA-2.CH8
mv Clipper.ch8 CLIPPER.CH8
mv Comic_Fans.ch8 COMIC_-1.CH8
mv Compression.ch8 COMPRE-1.CH8
mv Compression_Short.ch8 COMPRE-2.CH8
mv Compression_Square.ch8 COMPRE-3.CH8
mv Compression_Square_Short.ch8 COMPRE-4.CH8
mv Compression_Square_Tall_Alt.ch8 COMPRE-5.CH8
mv Compression_Square_Tall.ch8 COMPRE-6.CH8
mv Compression_Tall.ch8 COMPRE-7.CH8
mv Computer.ch8 COMPUTER.CH8
mv Computing_60s_Bold.ch8 COMPUT-1.CH8
mv Computing_60s.ch8 COMPUT-2.CH8
mv Computing_60s_Oblique.ch8 COMPUT-3.CH8
mv Conapt_Bold.ch8 CONAPT-1.CH8
mv Conapt.ch8 CONAPT.CH8
mv Conapt-Pro5.ch8 CONAPT-2.CH8
mv Conapt_Semi.ch8 CONAPT-3.CH8
mv Conveyance.ch8 CONVEY-1.CH8
mv Coolant.ch8 COOLANT.CH8
mv Crews.ch8 CREWS.CH8
mv Cushion.ch8 CUSHION.CH8
mv Cushion_Light.ch8 CUSHIO-1.CH8
mv Cushion_Narrow.ch8 CUSHIO-2.CH8
mv Cyberwire.ch8 CYBERW-1.CH8
mv Daddy_Cool.ch8 DADDY_-1.CH8
mv Datel_Replay.ch8 DATEL_-1.CH8
mv Datel_Tribute.ch8 DATEL_-2.CH8
mv Datel_Tron.ch8 DATEL_-3.CH8
mv Dead_Forest.ch8 DEAD_F-1.CH8
mv Deaf_Metal_2020.ch8 DEAF_M-1.CH8
mv Deaf_Metal_2020_Square.ch8 DEAF_M-2.CH8
mv Deaf_Metal.ch8 DEAF_M-3.CH8
mv Dean.ch8 DEAN.CH8
mv Decor.ch8 DECOR.CH8
mv Diamond.ch8 DIAMOND.CH8
mv District_Bold.ch8 DISTRI-1.CH8
mv District.ch8 DISTRICT.CH8
mv District_Comic.ch8 DISTRI-2.CH8
mv District_Digital_Bold.ch8 DISTRI-3.CH8
mv District_Digital.ch8 DISTRI-4.CH8
mv District_Digital_Compressed.ch8 DISTRI-5.CH8
mv District_Digital_Outline_Bold.ch8 DISTRI-6.CH8
mv District_Digital_Outline.ch8 DISTRI-7.CH8
mv District_Outline_Bold.ch8 DISTRI-8.CH8
mv District_Outline.ch8 DISTRI-9.CH8
mv District_Shadow_Bold.ch8 DISTR-10.CH8
mv District_Shadow.ch8 DISTR-11.CH8
mv Dunny_On_The_Wold.ch8 DUNNY_-1.CH8
mv Eclipse.ch8 ECLIPSE.CH8
mv Egyptian_Mercy_Bold.ch8 EGYPTI-1.CH8
mv Egyptian_Mercy.ch8 EGYPTI-2.CH8
mv Electromagnetic.ch8 ELECTR-1.CH8
mv Emmaline_Bold.ch8 EMMALI-1.CH8
mv Emmaline.ch8 EMMALINE.CH8
mv Emmaline_Heavy.ch8 EMMALI-3.CH8
mv Emmaline_Open.ch8 EMMALI-4.CH8
mv Envious_Bold.ch8 ENVIOU-1.CH8
mv Envious.ch8 ENVIOUS.CH8
mv Envious_Italic.ch8 ENVIOU-2.CH8
mv Envious_Serif_Bold.ch8 ENVIOU-3.CH8
mv Envious_Serif.ch8 ENVIOU-4.CH8
mv Everest_Bold.ch8 EVERES-1.CH8
mv Everest.ch8 EVEREST.CH8
mv Everest_Condensed.ch8 EVERES-2.CH8
mv Everest_Condensed_SemiBold.ch8 EVERES-3.CH8
mv Experiment88.ch8 EXPERI-1.CH8
mv Factor.ch8 FACTOR.CH8
mv Fatality.ch8 FATALITY.CH8
mv Firebird.ch8 FIREBIRD.CH8
mv First_Pass.ch8 FIRST_-1.CH8
mv Flamboyant.ch8 FLAMBO-1.CH8
mv Flick.ch8 FLICK.CH8
mv Florin.ch8 FLORIN.CH8
mv Forgotten_Bold.ch8 FORGOT-1.CH8
mv Forgotten.ch8 FORGOT-2.CH8
mv Forgotten_Heavy_Hand.ch8 FORGOT-3.CH8
mv Founded.ch8 FOUNDED.CH8
mv Founded_Clean.ch8 FOUNDE-1.CH8
mv Founded_Deco.ch8 FOUNDE-2.CH8
mv Founded_Deco_Open.ch8 FOUNDE-3.CH8
mv Fountain.ch8 FOUNTAIN.CH8
mv Fountain_Joined.ch8 FOUNTA-1.CH8
mv Franopix_Bold.ch8 FRANOP-1.CH8
mv Franopix.ch8 FRANOPIX.CH8
mv Franopix_Heavy.ch8 FRANOP-2.CH8
mv Fusion_Drive_Bold.ch8 FUSION-1.CH8
mv Fusion_Drive.ch8 FUSION-2.CH8
mv Gattars_Fork.ch8 GATTAR-1.CH8
mv Gattars_Fork_Script.ch8 GATTAR-2.CH8
mv Gemini.ch8 GEMINI.CH8
mv Gemini_Radar.ch8 GEMINI-1.CH8
mv Gemma.ch8 GEMMA.CH8
mv Gemma_Short_Lower.ch8 GEMMA_-1.CH8
mv Golden_Air_Bold.ch8 GOLDEN-1.CH8
mv Golden_Air.ch8 GOLDEN-2.CH8
mv Golden_Air_Rangers.ch8 GOLDEN-3.CH8
mv Golden_Air_SemiBold.ch8 GOLDEN-4.CH8
mv Halfling_Bold.ch8 HALFLI-1.CH8
mv Halfling.ch8 HALFLING.CH8
mv High_Noon_Bold.ch8 HIGH_N-1.CH8
mv High_Noon.ch8 HIGH_N-2.CH8
mv Homestead.ch8 HOMEST-1.CH8
mv Hourglass_Bold.ch8 HOURGL-1.CH8
mv Hourglass.ch8 HOURGL-2.CH8
mv Ident.ch8 IDENT.CH8
mv Inkscript_Bold.ch8 INKSCR-1.CH8
mv Inkscript.ch8 INKSCR-2.CH8
mv Ink_Stamp.ch8 INK_ST-1.CH8
mv Insigbyte_Bold.ch8 INSIGB-1.CH8
mv Insigbyte.ch8 INSIGB-2.CH8
mv Invasion_Bold.ch8 INVASI-1.CH8
mv Invasion.ch8 INVASION.CH8
mv Invitation_Sans.ch8 INVITA-1.CH8
mv Invitation_Serif_Bold.ch8 INVITA-2.CH8
mv Invitation_Serif.ch8 INVITA-3.CH8
mv Ion_Drive.ch8 ION_DR-1.CH8
mv Isofell.ch8 ISOFELL.CH8
mv Jam.ch8 JAM.CH8
mv Jam_Heavy.ch8 JAM_HE-1.CH8
mv Joshua.ch8 JOSHUA.CH8
mv Journey.ch8 JOURNEY.CH8
mv Kalopsia.ch8 KALOPSIA.CH8
mv Keytop.ch8 KEYTOP.CH8
mv Kindness_Bold.ch8 KINDNE-1.CH8
mv Kindness.ch8 KINDNESS.CH8
mv Koncrete.ch8 KONCRETE.CH8
mv Labyrinth.ch8 LABYRI-1.CH8
mv Lander_Bold.ch8 LANDER-1.CH8
mv Lander.ch8 LANDER.CH8
mv Lapse_Bold.ch8 LAPSE_-1.CH8
mv Lapse.ch8 LAPSE.CH8
mv Lapse_Condensed.ch8 LAPSE_-2.CH8
mv Lapse_Condensed_Semi_Bold.ch8 LAPSE_-3.CH8
mv Lapse_Narrow.ch8 LAPSE_-4.CH8
mv Localhost_Bold.ch8 LOCALH-1.CH8
mv Localhost.ch8 LOCALH-2.CH8
mv Mach4.ch8 MACH4.CH8
mv Mach4_Wide.ch8 MACH4_-1.CH8
mv Magic5_Bold.ch8 MAGIC5-1.CH8
mv Magic5.ch8 MAGIC5.CH8
mv Magnetic.ch8 MAGNETIC.CH8
mv Marais.ch8 MARAIS.CH8
mv Mild_West.ch8 MILD_W-1.CH8
mv Mutual.ch8 MUTUAL.CH8
mv Needlecast_Bold.ch8 NEEDLE-1.CH8
mv Needlecast.ch8 NEEDLE-2.CH8
mv Needlecast_Heavy.ch8 NEEDLE-3.CH8
mv Neoflow.ch8 NEOFLOW.CH8
mv Nibbles_Bold.ch8 NIBBLE-1.CH8
mv Nibbles.ch8 NIBBLES.CH8
mv Nicety_Bold.ch8 NICETY-1.CH8
mv Nicety.ch8 NICETY.CH8
mv Nicety_Semi_Bold.ch8 NICETY-2.CH8
mv No_Step.C64.ch8 NO_STE-1.CH8
mv No_Step.ch8 NO_STEP.CH8
mv No_Step_Lower.ch8 NO_STE-2.CH8
mv Noted.ch8 NOTED.CH8
mv Orbiter_Bold.ch8 ORBITE-1.CH8
mv Orbiter.ch8 ORBITER.CH8
mv Outer.ch8 OUTER.CH8
mv Outer_Serif.ch8 OUTER_-1.CH8
mv Outrunner_Inline.ch8 OUTRUN-1.CH8
mv Outrunner_Outline.ch8 OUTRUN-2.CH8
mv Panda.ch8 PANDA.CH8
mv Parchment.ch8 PARCHM-1.CH8
mv Phase_Shifter.ch8 PHASE_-1.CH8
mv Phase_Shifter_Solid.ch8 PHASE_-3.CH8
mv Pinhead.ch8 PINHEAD.CH8
mv Pitstop.ch8 PITSTOP.CH8
mv Pixharmonix.ch8 PIXHAR-1.CH8
mv Pixie_Bell.ch8 PIXIE_-1.CH8
mv Pixie_Bell_Stretch.ch8 PIXIE_-2.CH8
mv Pixie_Bold.ch8 PIXIE_-3.CH8
mv Pixie.ch8 PIXIE.CH8
mv Pixie_Digital.ch8 PIXIE_-5.CH8
mv Plato.ch8 PLATO.CH8
mv Plotter_Bold.ch8 PLOTTE-1.CH8
mv Plotter.ch8 PLOTTER.CH8
mv Plotter_Condensed.ch8 PLOTTE-2.CH8
mv Polaris.ch8 POLARIS.CH8
mv Precinct_0_Bit.ch8 PRECIN-1.CH8
mv Precinct_0.ch8 PRECIN-2.CH8
mv Precinct_0_Short.ch8 PRECIN-3.CH8
mv Precinct_0_Tiny.ch8 PRECIN-4.CH8
mv Precinct_180.ch8 PRECIN-6.CH8
mv Precinct_90.ch8 PRECIN-7.CH8
mv Prelude.ch8 PRELUDE.CH8
mv Primary_Target.ch8 PRIMAR-1.CH8
mv Prince.ch8 PRINCE.CH8
mv Prism.ch8 PRISM.CH8
mv Prism_Simplified.ch8 PRISM_-1.CH8
mv Pristine_Bold.ch8 PRISTI-1.CH8
mv Pristine.ch8 PRISTINE.CH8
mv Pristine_Decay.ch8 PRISTI-3.CH8
mv Proforma.ch8 PROFORMA.CH8
mv Proforma_Mid_Numeric.ch8 PROFOR-1.CH8
mv Proforma_Small_Numeric.ch8 PROFOR-2.CH8
mv Protractor.ch8 PROTRA-1.CH8
mv Punch.ch8 PUNCH.CH8
mv Quaked.ch8 QUAKED.CH8
mv Quantra.ch8 QUANTRA.CH8
mv Quasar.ch8 QUASAR.CH8
mv Quickshot.ch8 QUICKS-1.CH8
mv Ramscoop_Angled.ch8 RAMSCO-1.CH8
mv Ramscoop.ch8 RAMSCOOP.CH8
mv Raptor_Bold.ch8 RAPTOR-1.CH8
mv Raptor.ch8 RAPTOR.CH8
mv Raven_Bold.ch8 RAVEN_-1.CH8
mv Raven.ch8 RAVEN.CH8
mv Raven_SemiBold.ch8 RAVEN_-2.CH8
mv Razor.ch8 RAZOR.CH8
mv Razor_Rust.ch8 RAZOR_-1.CH8
mv Reactor.ch8 REACTOR.CH8
mv Reactor_Heavy.ch8 REACTO-1.CH8
mv Reactor_Heavy_Shine.ch8 REACTO-2.CH8
mv Reactor_Heavy_Stripe.ch8 REACTO-3.CH8
mv Reactor_Leak.ch8 REACTO-4.CH8
mv Reactor_Oblique.ch8 REACTO-5.CH8
mv Reactor_Serif.ch8 REACTO-6.CH8
mv Reactor_Zone.ch8 REACTO-7.CH8
mv Rebound_Open.ch8 REBOUN-1.CH8
mv Rebound_Sphere.ch8 REBOUN-2.CH8
mv Rebound_Wrap.ch8 REBOUN-3.CH8
mv Reflections.ch8 REFLEC-1.CH8
mv Reflections_Dark.ch8 REFLEC-2.CH8
mv Reflex.ch8 REFLEX.CH8
mv Revelation_Bold.ch8 REVELA-1.CH8
mv Revelation.ch8 REVELA-2.CH8
mv Reward.ch8 REWARD.CH8
mv Reward_Short.ch8 REWARD-1.CH8
mv Reynolds_Bold.ch8 REYNOL-1.CH8
mv Reynolds.ch8 REYNOLDS.CH8
mv Reynolds_SemiBold.ch8 REYNOL-2.CH8
mv Ricochet_Bold.ch8 RICOCH-1.CH8
mv Ricochet.ch8 RICOCHET.CH8
mv Riverbank.ch8 RIVERB-1.CH8
mv Riveter.ch8 RIVETER.CH8
mv Rosand.ch8 ROSAND.CH8
mv Runed.ch8 RUNED.CH8
mv Scribe-AGD-5.ch8 SCRIBE-1.CH8
mv Scribe_Bold.ch8 SCRIBE-2.CH8
mv Scribe.ch8 SCRIBE.CH8
mv Scribe_Condensed.ch8 SCRIBE-4.CH8
mv Scribe_Condensed_Lowercase.ch8 SCRIBE-5.CH8
mv Scribe_Condensed_Smaller_Lowercase.ch8 SCRIBE-6.CH8
mv Scribe_Eire.ch8 SCRIBE-8.CH8
mv Scribe_Hylean.ch8 SCRIBE-9.CH8
mv Scribe_Smaller_Lowercase.ch8 SCRIB-10.CH8
mv Scribe_Spaced.ch8 SCRIBE-3.CH8
mv Sector_One.ch8 SECTOR-1.CH8
mv Sector_Two.ch8 SECTOR-2.CH8
mv Sector_Zero.ch8 SECTOR-4.CH8
mv Security_Concepts.ch8 SECURI-1.CH8
mv Segment8.ch8 SEGMENT8.CH8
mv Shakedown.ch8 SHAKED-1.CH8
mv Shinobi_Extended.ch8 SHINOB-1.CH8
mv Shuriken.ch8 SHURIKEN.CH8
mv Sketcher_Bold.ch8 SKETCH-1.CH8
mv Sketcher.ch8 SKETCHER.CH8
mv Skid_Row.ch8 SKID_ROW.CH8
mv Sorcery.ch8 SORCERY.CH8
mv Space_Opera.ch8 SPACE_-1.CH8
mv Specmatic.ch8 SPECMA-1.CH8
mv Speedway_Bold.ch8 SPEEDW-1.CH8
mv Speedway.ch8 SPEEDWAY.CH8
mv Standstill.ch8 STANDS-1.CH8
mv Star_Ranger.ch8 STAR_R-1.CH8
mv Star_Ranger_Oblique.ch8 STAR_R-2.CH8
mv Stars.ch8 STARS.CH8
mv Stars_Square.ch8 STARS_-1.CH8
mv Stepper_Bold.ch8 STEPPE-1.CH8
mv Stepper.ch8 STEPPER.CH8
mv Stepper_Cut.ch8 STEPPE-2.CH8
mv Streetdoc.ch8 STREET-1.CH8
mv Striker_Bold.ch8 STRIKE-1.CH8
mv Striker.ch8 STRIKER.CH8
mv Striker_SemiBold.ch8 STRIKE-2.CH8
mv Submerged_Bold.ch8 SUBMER-1.CH8
mv Submerged.ch8 SUBMER-2.CH8
mv Syncwave_Bubble.ch8 SYNCWA-1.CH8
mv Syncwave.ch8 SYNCWAVE.CH8
mv Tenant_Bold.ch8 TENANT-1.CH8
mv Tenant.ch8 TENANT.CH8
mv Tenant_Digital.ch8 TENANT-2.CH8
mv Tentacle_Bold.ch8 TENTAC-1.CH8
mv Tentacle.ch8 TENTACLE.CH8
mv Tipped.ch8 TIPPED.CH8
mv Torment.ch8 TORMENT.CH8
mv Torque.ch8 TORQUE.CH8
mv Touch_Down.ch8 TOUCH_-1.CH8
mv Touch_Up.ch8 TOUCH_UP.CH8
mv Track40_Lower.ch8 TRACK4-1.CH8
mv Track40_Upper.ch8 TRACK4-2.CH8
mv Treatise.ch8 TREATISE.CH8
mv Trouble.ch8 TROUBLE.CH8
mv Truffle_Shuffle.ch8 TRUFFL-1.CH8
mv Tuner.ch8 TUNER.CH8
mv Tycho.ch8 TYCHO.CH8
mv Ultimatum.ch8 ULTIMA-1.CH8
mv Uncial.ch8 UNCIAL.CH8
mv Undead.ch8 UNDEAD.CH8
mv Valley.ch8 VALLEY.CH8
mv Valour.ch8 VALOUR.CH8
mv Valour_Sharp.ch8 VALOUR-1.CH8
mv Velocity.ch8 VELOCITY.CH8
mv Vertigo.ch8 VERTIGO.CH8
mv Vindicated.ch8 VINDIC-1.CH8
mv Watchface_Bold.ch8 WATCHF-1.CH8
mv Watchface.ch8 WATCHF-2.CH8
mv Waterlily.ch8 WATERL-1.CH8
mv Widget_Bold.ch8 WIDGET-1.CH8
mv Widget.ch8 WIDGET.CH8
mv Winterforge.ch8 WINTER-1.CH8
mv Xcelerant.ch8 XCELER-1.CH8
mv Xcerpt.ch8 XCERPT.CH8
mv Yaroze.ch8 YAROZE.CH8
mv Yaroze_SemiBold.ch8 YAROZE-1.CH8
mv You_Squared_Bold.ch8 YOU_SQ-1.CH8
mv You_Squared.ch8 YOU_SQ-2.CH8
mv You_Squared_Wide.ch8 YOU_SQ-3.CH8
mv ZX_Baveuse.ch8 ZX_BAV-1.CH8
mv ZX_Benguiat_Bold.ch8 ZX_BEN-1.CH8
mv ZX_Benguiat.ch8 ZX_BEN-2.CH8
mv ZX_Chicago.ch8 ZX_CHI-1.CH8
mv ZX_Chicago_Pod.ch8 ZX_CHI-2.CH8
mv ZX_Chicago_Twiggy.ch8 ZX_CHI-4.CH8
mv ZX_Courier_Bold.ch8 ZX_COU-1.CH8
mv ZX_Courier.ch8 ZX_COU-2.CH8
mv ZX_Eurostile.ch8 ZX_EUR-1.CH8
mv ZX_Eurostile_Wider.ch8 ZX_EUR-2.CH8
mv ZX_Extendomatic.ch8 ZX_EXT-1.CH8
mv ZX_Maverick.ch8 ZX_MAV-1.CH8
mv ZX_Megascope.ch8 ZX_MEG-1.CH8
mv ZX_OCR-B-Pro5.ch8 ZX_OCR-1.CH8
mv ZX_Palm_Bold.ch8 ZX_PAL-1.CH8
mv ZX_Palm.ch8 ZX_PALM.CH8
mv ZX_Peignot.ch8 ZX_PEI-1.CH8
mv ZX_Ramona_Bold.ch8 ZX_RAM-1.CH8
mv ZX_Ramona.ch8 ZX_RAM-3.CH8
mv ZX_Ramona_Closer.ch8 ZX_RAM-4.CH8
mv ZX_Rustproof.ch8 ZX_RUS-1.CH8
mv ZX_Sierra_Quest.ch8 ZX_SIE-1.CH8
mv ZX_System_X3.ch8 ZX_SYS-1.CH8
mv ZX_Times.ch8 ZX_TIMES.CH8
mv ZX_Venice.ch8 ZX_VEN-1.CH8
