mv ALTERE-1.CH8 Altered_Chrome_Bold.ch8
mv ALTERE-2.CH8 Altered_Chrome.ch8
mv ALTERE-3.CH8 Altered_Chrome_Script.ch8
mv ALTERE-4.CH8 Altered_Chrome_SemiBold.ch8
mv ANARCH-1.CH8 Anarchist.ch8
mv ANARCH-2.CH8 Anarchist-Heavy.ch8
mv ANARCH-3.CH8 Anarchist_Heavy.ch8
mv ANARCH-4.CH8 Anarchist_Short.ch8
mv ANCHOVY.CH8 Anchovy.ch8
mv ANVIL_-1.CH8 Anvil_Alternate.ch8
mv ANVIL.CH8 Anvil.ch8
mv AREA51.CH8 Area51.ch8
mv AREA51-1.CH8 Area51_Overwide.ch8
mv AREA51-2.CH8 Area51_Serif_Bold.ch8
mv AREA51-3.CH8 Area51_Serif.ch8
mv AROUND.CH8 Around.ch8
mv ATLAS.CH8 Atlas.ch8
mv AUTHOR-1.CH8 Authorized.ch8
mv AUTHOR-2.CH8 Authorized_Edge.ch8
mv BABYTE-1.CH8 Babyteeth.ch8
mv BAMBOO.CH8 Bamboo.ch8
mv BAUHAUS.CH8 Bauhaus.ch8
mv BEACHB-1.CH8 Beachball.ch8
mv BEACHB-2.CH8 Beachball_Short.ch8
mv BEASTLY.CH8 Beastly.ch8
mv BINNAC-1.CH8 Binnacle_Bold.ch8
mv BINNACLE.CH8 Binnacle.ch8
mv BINNAC-2.CH8 Binnacle_Oblique.ch8
mv BLOOD_-1.CH8 Blood_Rain.ch8
mv BROADW-1.CH8 Broadwary.ch8
mv BUBBLE-1.CH8 Bubblegum.ch8
mv BUBBLE-2.CH8 Bubblegum_Round.ch8
mv BYTELE-1.CH8 Byteletter.ch8
mv CABARE-1.CH8 Cabaret_Bold.ch8
mv CABARET.CH8 Cabaret.ch8
mv CABARE-2.CH8 Cabaret-Pro5.ch8
mv CABARE-3.CH8 Cabaret_Semi_Bold.ch8
mv CAGE_B-1.CH8 Cage_Bold.ch8
mv CAGE.CH8 Cage.ch8
mv CALSTONE.CH8 Calstone.ch8
mv CALSTO-1.CH8 Calstone_Heavy.ch8
mv CAPRICA.CH8 Caprica.ch8
mv CARTON-1.CH8 Carton_Bold.ch8
mv CARTON.CH8 Carton.ch8
mv CARTON-2.CH8 Carton_Tall_Caps.ch8
mv CHEST_-1.CH8 Chest_Burster_Bold.ch8
mv CHEST_-2.CH8 Chest_Burster.ch8
mv CHIT_B-1.CH8 Chit_Bold.ch8
mv CHIT.CH8 Chit.ch8
mv CHUNKY-1.CH8 Chunky_Monkey.ch8
mv CINEMA-1.CH8 Cinema_Bold.ch8
mv CINEMA.CH8 Cinema.ch8
mv CINEMA-2.CH8 Cinema_Condensed.ch8
mv CLIPPER.CH8 Clipper.ch8
mv COMIC_-1.CH8 Comic_Fans.ch8
mv COMPRE-1.CH8 Compression.ch8
mv COMPRE-2.CH8 Compression_Short.ch8
mv COMPRE-3.CH8 Compression_Square.ch8
mv COMPRE-4.CH8 Compression_Square_Short.ch8
mv COMPRE-5.CH8 Compression_Square_Tall_Alt.ch8
mv COMPRE-6.CH8 Compression_Square_Tall.ch8
mv COMPRE-7.CH8 Compression_Tall.ch8
mv COMPUTER.CH8 Computer.ch8
mv COMPUT-1.CH8 Computing_60s_Bold.ch8
mv COMPUT-2.CH8 Computing_60s.ch8
mv COMPUT-3.CH8 Computing_60s_Oblique.ch8
mv CONAPT-1.CH8 Conapt_Bold.ch8
mv CONAPT.CH8 Conapt.ch8
mv CONAPT-2.CH8 Conapt-Pro5.ch8
mv CONAPT-3.CH8 Conapt_Semi.ch8
mv CONVEY-1.CH8 Conveyance.ch8
mv COOLANT.CH8 Coolant.ch8
mv CREWS.CH8 Crews.ch8
mv CUSHION.CH8 Cushion.ch8
mv CUSHIO-1.CH8 Cushion_Light.ch8
mv CUSHIO-2.CH8 Cushion_Narrow.ch8
mv CYBERW-1.CH8 Cyberwire.ch8
mv DADDY_-1.CH8 Daddy_Cool.ch8
mv DATEL_-1.CH8 Datel_Replay.ch8
mv DATEL_-2.CH8 Datel_Tribute.ch8
mv DATEL_-3.CH8 Datel_Tron.ch8
mv DEAD_F-1.CH8 Dead_Forest.ch8
mv DEAF_M-1.CH8 Deaf_Metal_2020.ch8
mv DEAF_M-2.CH8 Deaf_Metal_2020_Square.ch8
mv DEAF_M-3.CH8 Deaf_Metal.ch8
mv DEAN.CH8 Dean.ch8
mv DECOR.CH8 Decor.ch8
mv DIAMOND.CH8 Diamond.ch8
mv DISTRI-1.CH8 District_Bold.ch8
mv DISTRICT.CH8 District.ch8
mv DISTRI-2.CH8 District_Comic.ch8
mv DISTRI-3.CH8 District_Digital_Bold.ch8
mv DISTRI-4.CH8 District_Digital.ch8
mv DISTRI-5.CH8 District_Digital_Compressed.ch8
mv DISTRI-6.CH8 District_Digital_Outline_Bold.ch8
mv DISTRI-7.CH8 District_Digital_Outline.ch8
mv DISTRI-8.CH8 District_Outline_Bold.ch8
mv DISTRI-9.CH8 District_Outline.ch8
mv DISTR-10.CH8 District_Shadow_Bold.ch8
mv DISTR-11.CH8 District_Shadow.ch8
mv DUNNY_-1.CH8 Dunny_On_The_Wold.ch8
mv ECLIPSE.CH8 Eclipse.ch8
mv EGYPTI-1.CH8 Egyptian_Mercy_Bold.ch8
mv EGYPTI-2.CH8 Egyptian_Mercy.ch8
mv ELECTR-1.CH8 Electromagnetic.ch8
mv EMMALI-1.CH8 Emmaline_Bold.ch8
mv EMMALINE.CH8 Emmaline.ch8
mv EMMALI-3.CH8 Emmaline_Heavy.ch8
mv EMMALI-4.CH8 Emmaline_Open.ch8
mv ENVIOU-1.CH8 Envious_Bold.ch8
mv ENVIOUS.CH8 Envious.ch8
mv ENVIOU-2.CH8 Envious_Italic.ch8
mv ENVIOU-3.CH8 Envious_Serif_Bold.ch8
mv ENVIOU-4.CH8 Envious_Serif.ch8
mv EVERES-1.CH8 Everest_Bold.ch8
mv EVEREST.CH8 Everest.ch8
mv EVERES-2.CH8 Everest_Condensed.ch8
mv EVERES-3.CH8 Everest_Condensed_SemiBold.ch8
mv EXPERI-1.CH8 Experiment88.ch8
mv FACTOR.CH8 Factor.ch8
mv FATALITY.CH8 Fatality.ch8
mv FIREBIRD.CH8 Firebird.ch8
mv FIRST_-1.CH8 First_Pass.ch8
mv FLAMBO-1.CH8 Flamboyant.ch8
mv FLICK.CH8 Flick.ch8
mv FLORIN.CH8 Florin.ch8
mv FORGOT-1.CH8 Forgotten_Bold.ch8
mv FORGOT-2.CH8 Forgotten.ch8
mv FORGOT-3.CH8 Forgotten_Heavy_Hand.ch8
mv FOUNDED.CH8 Founded.ch8
mv FOUNDE-1.CH8 Founded_Clean.ch8
mv FOUNDE-2.CH8 Founded_Deco.ch8
mv FOUNDE-3.CH8 Founded_Deco_Open.ch8
mv FOUNTAIN.CH8 Fountain.ch8
mv FOUNTA-1.CH8 Fountain_Joined.ch8
mv FRANOP-1.CH8 Franopix_Bold.ch8
mv FRANOPIX.CH8 Franopix.ch8
mv FRANOP-2.CH8 Franopix_Heavy.ch8
mv FUSION-1.CH8 Fusion_Drive_Bold.ch8
mv FUSION-2.CH8 Fusion_Drive.ch8
mv GATTAR-1.CH8 Gattars_Fork.ch8
mv GATTAR-2.CH8 Gattars_Fork_Script.ch8
mv GEMINI.CH8 Gemini.ch8
mv GEMINI-1.CH8 Gemini_Radar.ch8
mv GEMMA.CH8 Gemma.ch8
mv GEMMA_-1.CH8 Gemma_Short_Lower.ch8
mv GOLDEN-1.CH8 Golden_Air_Bold.ch8
mv GOLDEN-2.CH8 Golden_Air.ch8
mv GOLDEN-3.CH8 Golden_Air_Rangers.ch8
mv GOLDEN-4.CH8 Golden_Air_SemiBold.ch8
mv HALFLI-1.CH8 Halfling_Bold.ch8
mv HALFLING.CH8 Halfling.ch8
mv HIGH_N-1.CH8 High_Noon_Bold.ch8
mv HIGH_N-2.CH8 High_Noon.ch8
mv HOMEST-1.CH8 Homestead.ch8
mv HOURGL-1.CH8 Hourglass_Bold.ch8
mv HOURGL-2.CH8 Hourglass.ch8
mv IDENT.CH8 Ident.ch8
mv INKSCR-1.CH8 Inkscript_Bold.ch8
mv INKSCR-2.CH8 Inkscript.ch8
mv INK_ST-1.CH8 Ink_Stamp.ch8
mv INSIGB-1.CH8 Insigbyte_Bold.ch8
mv INSIGB-2.CH8 Insigbyte.ch8
mv INVASI-1.CH8 Invasion_Bold.ch8
mv INVASION.CH8 Invasion.ch8
mv INVITA-1.CH8 Invitation_Sans.ch8
mv INVITA-2.CH8 Invitation_Serif_Bold.ch8
mv INVITA-3.CH8 Invitation_Serif.ch8
mv ION_DR-1.CH8 Ion_Drive.ch8
mv ISOFELL.CH8 Isofell.ch8
mv JAM.CH8 Jam.ch8
mv JAM_HE-1.CH8 Jam_Heavy.ch8
mv JOSHUA.CH8 Joshua.ch8
mv JOURNEY.CH8 Journey.ch8
mv KALOPSIA.CH8 Kalopsia.ch8
mv KEYTOP.CH8 Keytop.ch8
mv KINDNE-1.CH8 Kindness_Bold.ch8
mv KINDNESS.CH8 Kindness.ch8
mv KONCRETE.CH8 Koncrete.ch8
mv LABYRI-1.CH8 Labyrinth.ch8
mv LANDER-1.CH8 Lander_Bold.ch8
mv LANDER.CH8 Lander.ch8
mv LAPSE_-1.CH8 Lapse_Bold.ch8
mv LAPSE.CH8 Lapse.ch8
mv LAPSE_-2.CH8 Lapse_Condensed.ch8
mv LAPSE_-3.CH8 Lapse_Condensed_Semi_Bold.ch8
mv LAPSE_-4.CH8 Lapse_Narrow.ch8
mv LOCALH-1.CH8 Localhost_Bold.ch8
mv LOCALH-2.CH8 Localhost.ch8
mv MACH4.CH8 Mach4.ch8
mv MACH4_-1.CH8 Mach4_Wide.ch8
mv MAGIC5-1.CH8 Magic5_Bold.ch8
mv MAGIC5.CH8 Magic5.ch8
mv MAGNETIC.CH8 Magnetic.ch8
mv MARAIS.CH8 Marais.ch8
mv MILD_W-1.CH8 Mild_West.ch8
mv MUTUAL.CH8 Mutual.ch8
mv NEEDLE-1.CH8 Needlecast_Bold.ch8
mv NEEDLE-2.CH8 Needlecast.ch8
mv NEEDLE-3.CH8 Needlecast_Heavy.ch8
mv NEOFLOW.CH8 Neoflow.ch8
mv NIBBLE-1.CH8 Nibbles_Bold.ch8
mv NIBBLES.CH8 Nibbles.ch8
mv NICETY-1.CH8 Nicety_Bold.ch8
mv NICETY.CH8 Nicety.ch8
mv NICETY-2.CH8 Nicety_Semi_Bold.ch8
mv NO_STE-1.CH8 No_Step.C64.ch8
mv NO_STEP.CH8 No_Step.ch8
mv NO_STE-2.CH8 No_Step_Lower.ch8
mv NOTED.CH8 Noted.ch8
mv ORBITE-1.CH8 Orbiter_Bold.ch8
mv ORBITER.CH8 Orbiter.ch8
mv OUTER.CH8 Outer.ch8
mv OUTER_-1.CH8 Outer_Serif.ch8
mv OUTRUN-1.CH8 Outrunner_Inline.ch8
mv OUTRUN-2.CH8 Outrunner_Outline.ch8
mv PANDA.CH8 Panda.ch8
mv PARCHM-1.CH8 Parchment.ch8
mv PHASE_-1.CH8 Phase_Shifter.ch8
mv PHASE_-3.CH8 Phase_Shifter_Solid.ch8
mv PINHEAD.CH8 Pinhead.ch8
mv PITSTOP.CH8 Pitstop.ch8
mv PIXHAR-1.CH8 Pixharmonix.ch8
mv PIXIE_-1.CH8 Pixie_Bell.ch8
mv PIXIE_-2.CH8 Pixie_Bell_Stretch.ch8
mv PIXIE_-3.CH8 Pixie_Bold.ch8
mv PIXIE.CH8 Pixie.ch8
mv PIXIE_-5.CH8 Pixie_Digital.ch8
mv PLATO.CH8 Plato.ch8
mv PLOTTE-1.CH8 Plotter_Bold.ch8
mv PLOTTER.CH8 Plotter.ch8
mv PLOTTE-2.CH8 Plotter_Condensed.ch8
mv POLARIS.CH8 Polaris.ch8
mv PRECIN-1.CH8 Precinct_0_Bit.ch8
mv PRECIN-2.CH8 Precinct_0.ch8
mv PRECIN-3.CH8 Precinct_0_Short.ch8
mv PRECIN-4.CH8 Precinct_0_Tiny.ch8
mv PRECIN-6.CH8 Precinct_180.ch8
mv PRECIN-7.CH8 Precinct_90.ch8
mv PRELUDE.CH8 Prelude.ch8
mv PRIMAR-1.CH8 Primary_Target.ch8
mv PRINCE.CH8 Prince.ch8
mv PRISM.CH8 Prism.ch8
mv PRISM_-1.CH8 Prism_Simplified.ch8
mv PRISTI-1.CH8 Pristine_Bold.ch8
mv PRISTINE.CH8 Pristine.ch8
mv PRISTI-3.CH8 Pristine_Decay.ch8
mv PROFORMA.CH8 Proforma.ch8
mv PROFOR-1.CH8 Proforma_Mid_Numeric.ch8
mv PROFOR-2.CH8 Proforma_Small_Numeric.ch8
mv PROTRA-1.CH8 Protractor.ch8
mv PUNCH.CH8 Punch.ch8
mv QUAKED.CH8 Quaked.ch8
mv QUANTRA.CH8 Quantra.ch8
mv QUASAR.CH8 Quasar.ch8
mv QUICKS-1.CH8 Quickshot.ch8
mv RAMSCO-1.CH8 Ramscoop_Angled.ch8
mv RAMSCOOP.CH8 Ramscoop.ch8
mv RAPTOR-1.CH8 Raptor_Bold.ch8
mv RAPTOR.CH8 Raptor.ch8
mv RAVEN_-1.CH8 Raven_Bold.ch8
mv RAVEN.CH8 Raven.ch8
mv RAVEN_-2.CH8 Raven_SemiBold.ch8
mv RAZOR.CH8 Razor.ch8
mv RAZOR_-1.CH8 Razor_Rust.ch8
mv REACTOR.CH8 Reactor.ch8
mv REACTO-1.CH8 Reactor_Heavy.ch8
mv REACTO-2.CH8 Reactor_Heavy_Shine.ch8
mv REACTO-3.CH8 Reactor_Heavy_Stripe.ch8
mv REACTO-4.CH8 Reactor_Leak.ch8
mv REACTO-5.CH8 Reactor_Oblique.ch8
mv REACTO-6.CH8 Reactor_Serif.ch8
mv REACTO-7.CH8 Reactor_Zone.ch8
mv REBOUN-1.CH8 Rebound_Open.ch8
mv REBOUN-2.CH8 Rebound_Sphere.ch8
mv REBOUN-3.CH8 Rebound_Wrap.ch8
mv REFLEC-1.CH8 Reflections.ch8
mv REFLEC-2.CH8 Reflections_Dark.ch8
mv REFLEX.CH8 Reflex.ch8
mv REVELA-1.CH8 Revelation_Bold.ch8
mv REVELA-2.CH8 Revelation.ch8
mv REWARD.CH8 Reward.ch8
mv REWARD-1.CH8 Reward_Short.ch8
mv REYNOL-1.CH8 Reynolds_Bold.ch8
mv REYNOLDS.CH8 Reynolds.ch8
mv REYNOL-2.CH8 Reynolds_SemiBold.ch8
mv RICOCH-1.CH8 Ricochet_Bold.ch8
mv RICOCHET.CH8 Ricochet.ch8
mv RIVERB-1.CH8 Riverbank.ch8
mv RIVETER.CH8 Riveter.ch8
mv ROSAND.CH8 Rosand.ch8
mv RUNED.CH8 Runed.ch8
mv SCRIBE-1.CH8 Scribe-AGD-5.ch8
mv SCRIBE-2.CH8 Scribe_Bold.ch8
mv SCRIBE.CH8 Scribe.ch8
mv SCRIBE-4.CH8 Scribe_Condensed.ch8
mv SCRIBE-5.CH8 Scribe_Condensed_Lowercase.ch8
mv SCRIBE-6.CH8 Scribe_Condensed_Smaller_Lowercase.ch8
mv SCRIBE-8.CH8 Scribe_Eire.ch8
mv SCRIBE-9.CH8 Scribe_Hylean.ch8
mv SCRIB-10.CH8 Scribe_Smaller_Lowercase.ch8
mv SCRIBE-3.CH8 Scribe_Spaced.ch8
mv SECTOR-1.CH8 Sector_One.ch8
mv SECTOR-2.CH8 Sector_Two.ch8
mv SECTOR-4.CH8 Sector_Zero.ch8
mv SECURI-1.CH8 Security_Concepts.ch8
mv SEGMENT8.CH8 Segment8.ch8
mv SHAKED-1.CH8 Shakedown.ch8
mv SHINOB-1.CH8 Shinobi_Extended.ch8
mv SHURIKEN.CH8 Shuriken.ch8
mv SKETCH-1.CH8 Sketcher_Bold.ch8
mv SKETCHER.CH8 Sketcher.ch8
mv SKID_ROW.CH8 Skid_Row.ch8
mv SORCERY.CH8 Sorcery.ch8
mv SPACE_-1.CH8 Space_Opera.ch8
mv SPECMA-1.CH8 Specmatic.ch8
mv SPEEDW-1.CH8 Speedway_Bold.ch8
mv SPEEDWAY.CH8 Speedway.ch8
mv STANDS-1.CH8 Standstill.ch8
mv STAR_R-1.CH8 Star_Ranger.ch8
mv STAR_R-2.CH8 Star_Ranger_Oblique.ch8
mv STARS.CH8 Stars.ch8
mv STARS_-1.CH8 Stars_Square.ch8
mv STEPPE-1.CH8 Stepper_Bold.ch8
mv STEPPER.CH8 Stepper.ch8
mv STEPPE-2.CH8 Stepper_Cut.ch8
mv STREET-1.CH8 Streetdoc.ch8
mv STRIKE-1.CH8 Striker_Bold.ch8
mv STRIKER.CH8 Striker.ch8
mv STRIKE-2.CH8 Striker_SemiBold.ch8
mv SUBMER-1.CH8 Submerged_Bold.ch8
mv SUBMER-2.CH8 Submerged.ch8
mv SYNCWA-1.CH8 Syncwave_Bubble.ch8
mv SYNCWAVE.CH8 Syncwave.ch8
mv TENANT-1.CH8 Tenant_Bold.ch8
mv TENANT.CH8 Tenant.ch8
mv TENANT-2.CH8 Tenant_Digital.ch8
mv TENTAC-1.CH8 Tentacle_Bold.ch8
mv TENTACLE.CH8 Tentacle.ch8
mv TIPPED.CH8 Tipped.ch8
mv TORMENT.CH8 Torment.ch8
mv TORQUE.CH8 Torque.ch8
mv TOUCH_-1.CH8 Touch_Down.ch8
mv TOUCH_UP.CH8 Touch_Up.ch8
mv TRACK4-1.CH8 Track40_Lower.ch8
mv TRACK4-2.CH8 Track40_Upper.ch8
mv TREATISE.CH8 Treatise.ch8
mv TROUBLE.CH8 Trouble.ch8
mv TRUFFL-1.CH8 Truffle_Shuffle.ch8
mv TUNER.CH8 Tuner.ch8
mv TYCHO.CH8 Tycho.ch8
mv ULTIMA-1.CH8 Ultimatum.ch8
mv UNCIAL.CH8 Uncial.ch8
mv UNDEAD.CH8 Undead.ch8
mv VALLEY.CH8 Valley.ch8
mv VALOUR.CH8 Valour.ch8
mv VALOUR-1.CH8 Valour_Sharp.ch8
mv VELOCITY.CH8 Velocity.ch8
mv VERTIGO.CH8 Vertigo.ch8
mv VINDIC-1.CH8 Vindicated.ch8
mv WATCHF-1.CH8 Watchface_Bold.ch8
mv WATCHF-2.CH8 Watchface.ch8
mv WATERL-1.CH8 Waterlily.ch8
mv WIDGET-1.CH8 Widget_Bold.ch8
mv WIDGET.CH8 Widget.ch8
mv WINTER-1.CH8 Winterforge.ch8
mv XCELER-1.CH8 Xcelerant.ch8
mv XCERPT.CH8 Xcerpt.ch8
mv YAROZE.CH8 Yaroze.ch8
mv YAROZE-1.CH8 Yaroze_SemiBold.ch8
mv YOU_SQ-1.CH8 You_Squared_Bold.ch8
mv YOU_SQ-2.CH8 You_Squared.ch8
mv YOU_SQ-3.CH8 You_Squared_Wide.ch8
mv ZX_BAV-1.CH8 ZX_Baveuse.ch8
mv ZX_BEN-1.CH8 ZX_Benguiat_Bold.ch8
mv ZX_BEN-2.CH8 ZX_Benguiat.ch8
mv ZX_CHI-1.CH8 ZX_Chicago.ch8
mv ZX_CHI-2.CH8 ZX_Chicago_Pod.ch8
mv ZX_CHI-4.CH8 ZX_Chicago_Twiggy.ch8
mv ZX_COU-1.CH8 ZX_Courier_Bold.ch8
mv ZX_COU-2.CH8 ZX_Courier.ch8
mv ZX_EUR-1.CH8 ZX_Eurostile.ch8
mv ZX_EUR-2.CH8 ZX_Eurostile_Wider.ch8
mv ZX_EXT-1.CH8 ZX_Extendomatic.ch8
mv ZX_MAV-1.CH8 ZX_Maverick.ch8
mv ZX_MEG-1.CH8 ZX_Megascope.ch8
mv ZX_OCR-1.CH8 ZX_OCR-B-Pro5.ch8
mv ZX_PAL-1.CH8 ZX_Palm_Bold.ch8
mv ZX_PALM.CH8 ZX_Palm.ch8
mv ZX_PEI-1.CH8 ZX_Peignot.ch8
mv ZX_RAM-1.CH8 ZX_Ramona_Bold.ch8
mv ZX_RAM-3.CH8 ZX_Ramona.ch8
mv ZX_RAM-4.CH8 ZX_Ramona_Closer.ch8
mv ZX_RUS-1.CH8 ZX_Rustproof.ch8
mv ZX_SIE-1.CH8 ZX_Sierra_Quest.ch8
mv ZX_SYS-1.CH8 ZX_System_X3.ch8
mv ZX_TIMES.CH8 ZX_Times.ch8
mv ZX_VEN-1.CH8 ZX_Venice.ch8
